# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 03:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ContactsApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('codUserContact', models.AutoField(primary_key=True, serialize=False)),
                ('idContact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ContactsApp.Contact', verbose_name='Contacto')),
                ('idUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID de Usuario')),
            ],
        ),
    ]
