# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('idContact', models.AutoField(primary_key=True, serialize=False)),
                ('listName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de Lista')),
                ('businessName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de Negocios')),
                ('contactName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de Contacto')),
                ('address1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Direccion 1')),
                ('address2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Direccion 2')),
                ('address3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Direccion 3')),
                ('address4', models.CharField(blank=True, max_length=250, null=True, verbose_name='Direccion 4')),
                ('postCode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Codigo Postal')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('categories', models.CharField(blank=True, choices=[('wo', 'Taller'), ('fr', 'Amigo'), ('cl', 'Club'), ('su', 'Proveedor')], max_length=50, null=True, verbose_name='Categorias')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('deleted', models.BooleanField(verbose_name='Eliminado')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
            ],
        ),
    ]
