# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address1',
            field=models.CharField(default=0, max_length=250, verbose_name='Direccion 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='categories',
            field=models.CharField(blank=True, choices=[('fr', 'Amigo'), ('su', 'Proveedor'), ('wo', 'Taller'), ('cl', 'Club')], max_length=50, null=True, verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contactName',
            field=models.CharField(default=0, max_length=50, verbose_name='Nombre de Contacto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='listName',
            field=models.CharField(default=0, max_length=50, verbose_name='Nombre de Lista'),
            preserve_default=False,
        ),
    ]
