# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactsApp', '0002_auto_20171001_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='categories',
            field=models.CharField(blank=True, choices=[('cl', 'Club'), ('fr', 'Amigo'), ('su', 'Proveedor'), ('wo', 'Taller')], max_length=50, null=True, verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='picture',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='profile/photos', verbose_name='Imagen'),
        ),
    ]
